[build]
  command = "git submodule update --init --recursive && hugo --gc --minify"
  publish = "public"

[build.environment]
  HUGO_VERSION = "0.152.2"
  HUGO_ENV = "production"
  HUGO_CACHEDIR = "/tmp/hugo_cache"
